export const competitionArr = [
  {
    coin: "Solana (SOL)",
    image: "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/images/bg-1.png",
    name: "Ahoy! Meme Matey",
    description: "Registration on the platform and at least five shares",
    invest: 340,
    participant: 200,
    id: "098761235456789",
  },
  {
    coin: "Solana (SOL)",
    image: "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/images/bg-2.png",
    name: "Seafaring Scallywag",
    description: "At least 10 shares and at least 20 likes from other users",
    invest: 9123,
    participant: 300,
    id: "098712365456789",
  },
  {
    coin: "Solana (SOL)",
    image: "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/images/bg-3.png",
    name: "Jolly Roger Jester",
    description: "20 shares, at least 50 likes and at least 5 comments.",
    invest: 4000,
    participant: 444,
    id: "098765456789",
  },
  {
    coin: "Solana (SOL)",
    image: "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/images/bg-8.png",
    name: "Scurvy Meme Swashbuckler",
    description: "40 memes, 100 likes, comment on 10 memes and get at least 10 comments",
    invest: 300,
    participant: 200,
    id: "098765456789",
  },
  {
    coin: "Solana (SOL)",
    image: "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/images/bg-4.png",
    name: "Buccaneer of Banter",
    description: "60 memes, getting 200 likes, making 50 comments and getting at least 50 comments. / participating in at least 5 contests",
    invest: 300,
    participant: 200,
    id: "098765456789",
  },
  {
    coin: "Solana (SOL)",
    image: "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/images/bg-5.png",
    name: "Pirate Poet of Laughs",
    description:
      "80 memes, getting 500 likes, commenting 100 times and getting at least 100 comments from memes / participating in at least 10 contests",
    participant: 200,
    id: "098765456789",
    invest: 3000,
  },
  {
    coin: "Solana (SOL)",
    image: "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/images/bg-6.png",
    name: "Privateer of Puns",
    description: "Share 100 memes, get 750 likes, 250 comments, and get at least 200 comments from memes / participate in at least 20 contests",
    invest: 340,
    participant: 200,
    id: "098765456789",
  },
  {
    coin: "Solana (SOL)",
    image: "https://raw.githubusercontent.com/mantinedev/mantine/master/.demo/images/bg-7.png",
    name: "Corsair of Comedy",
    description: "Share 200 memes, get 1500 likes, make 500 comments and get at least 500 comments from memes / participate in at least 50 contests",
    participant: 200,
    id: "098765456789",
    invest: 9123,
  },
];

export const memeData = [
  {
    width: 500,
    image_name: "https://i.imgflip.com/75wrsn.jpg",
    captions: [
      {
        x: 75,
        y: 50,
        borderColor: "#000",
        fontColor: "#ffffff",
        fontSize: 20,
        fontFamily: null,
        text: "Meme text goes here",
        width: 350,
        height: 41,
      },
      {
        x: 75,
        y: 200,
        borderColor: "#000",
        fontColor: "#ffffff",
        fontSize: 20,
        fontFamily: null,
        text: "Meme text goes here",
        width: 350,
        height: 41,
      },
    ],
  },
];
